# Generated by Django 4.2.16 on 2024-12-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IDGenie', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='IDGenie.comment'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
