# Generated by Django 4.2.16 on 2024-12-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDGenie', '0003_comment_parent_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='thumbs_down_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='thumbs_up_count',
            field=models.IntegerField(default=0),
        ),
    ]
