# Generated by Django 4.2.16 on 2024-12-27 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IDGenie', '0005_comment_disliked_by_comment_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='disliked_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='liked_by',
        ),
        migrations.CreateModel(
            name='UserCommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDGenie.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
